### ISSUE TITLE
add local notification

### ISSUE THREAD

**Issue by toby20130333** [beemaster/osxnotifytest#1]
NSUserNotification *notification = [[NSUserNotification alloc] init];
notification.title = @"Title";
notification.subtitle = @"subTitle";
notification.informativeText = @"details";

/*
//设置通知提交的时间 set notify commit time
notification.deliveryDate = [NSDate dateWithTimeIntervalSinceNow:5];
//设置通知的循环(必须大于1分钟，估计是防止软件刷屏) set notify repeat
NSDateComponents *dateComponents = [[NSDateComponents alloc] init];
[dateComponents setSecond:70];
notification.deliveryRepeatInterval = dateComponents;
*/

//只有当用户设置为提示模式时，才会显示按钮 
notification.hasActionButton = YES;
notification.actionButtonTitle = @"OK";
notification.otherButtonTitle = @"Cancel";

you can get the workground http://www.tanhao.me/pieces/517.html/

**Comment by beemaster** [comment]
The problem was missing CFBundleIdentifier in Info.plist. See: https://github.com/beemaster/osxnotifytest/commit/fa4154eebf9ffa51f9f9e5de5d12239c18d02370

**Comment by toby20130333** [comment]
But I cann't modify the plist file,and it can be OK

**Comment by beemaster** [comment]
Well, for me it was the reason, I don't know why
